"use client";

import { useMemo, useState } from "react";

type Locale="nl"|"en";
type Step="today"|"staff"|"order"|"delivery"|"count"|"close"|"copilot";

const copy={
  nl:{lang:"nl",demo:"Interactieve demo",venue:"CLINIQ Amsterdam",date:"Vrijdag 31 juli",today:"Vandaag",staff:"Bezetting",order:"Inkoop",delivery:"Ontvangst",count:"Telling",close:"Afsluiten",copilot:"Copilot",expected:"620 gasten verwacht",risk:"risico’s vóór opening",staffRisk:"Open bardienst 23:00–05:00",stockRisk:"Vodka onder benodigd niveau",next:"Volgende beste actie",review:"Open workflow",assign:"Wijs Mila toe",publish:"Publiceer versie 4",approve:"Keur bestelling goed",receive:"Ontvang 18 van 24 flessen",saveCount:"Sla telling op",recordWaste:"Registreer breuk",finish:"Keur afsluiting goed",ask:"Waarom viel de marge?",evidence:"Onderliggend bewijs",done:"Afgerond",synthetic:"Alle data is synthetisch en blijft alleen in deze demosessie."},
  en:{lang:"en",demo:"Interactive demo",venue:"CLINIQ Amsterdam",date:"Friday 31 July",today:"Today",staff:"Staffing",order:"Purchasing",delivery:"Receiving",count:"Count",close:"Close",copilot:"Copilot",expected:"620 guests expected",risk:"risks before opening",staffRisk:"Open bar shift 23:00–05:00",stockRisk:"Vodka below required level",next:"Next best action",review:"Open workflow",assign:"Assign Mila",publish:"Publish version 4",approve:"Approve order",receive:"Receive 18 of 24 bottles",saveCount:"Save count",recordWaste:"Record breakage",finish:"Approve close",ask:"Why did margin fall?",evidence:"Underlying evidence",done:"Completed",synthetic:"All data is synthetic and remains in this demo session only."},
} as const;

export function OperatingDemo({onExit}:{onExit:()=>void}){
  const [locale,setLocale]=useState<Locale>("nl");
  const [step,setStep]=useState<Step>("today");
  const [assigned,setAssigned]=useState(false);
  const [published,setPublished]=useState(false);
  const [ordered,setOrdered]=useState(false);
  const [received,setReceived]=useState(0);
  const [counted,setCounted]=useState(false);
  const [waste,setWaste]=useState(0);
  const [closed,setClosed]=useState(false);
  const [answer,setAnswer]=useState(false);
  const t=copy[locale];
  const stock=useMemo(()=>42+received-waste,[received,waste]);
  const risks=(published?0:1)+(stock<54?1:0)+(closed?0:1);
  const nav:[Step,string][]=[["today",t.today],["staff",t.staff],["order",t.order],["delivery",t.delivery],["count",t.count],["close",t.close],["copilot",t.copilot]];
  const go=(target:Step)=>setStep(target);

  return <div className="ops-demo">
    <aside>
      <button className="ops-brand" onClick={onExit}><span>N</span><b>NightProfit</b></button>
      <div className="ops-context"><span>CL</span><div><b>{t.venue}</b><small>{t.date}</small></div></div>
      <nav aria-label={t.demo}>{nav.map(([id,label])=><button key={id} className={step===id?"active":""} onClick={()=>go(id)}><span>{label.slice(0,2).toUpperCase()}</span>{label}{id==="today"&&risks>0?<em>{risks}</em>:null}</button>)}</nav>
      <div className="demo-safety"><b>{t.demo}</b><p>{t.synthetic}</p></div>
    </aside>
    <main>
      <header className="ops-topbar">
        <div><span>{t.venue}</span><b>/</b><strong>{nav.find(([id])=>id===step)?.[1]}</strong></div>
        <div><button onClick={()=>go("today")}>{t.date}</button><select aria-label={locale==="nl"?"Taal":"Language"} value={locale} onChange={event=>setLocale(event.target.value as Locale)}><option value="nl">NL</option><option value="en">EN</option></select><button onClick={onExit}>{locale==="nl"?"Sluiten":"Exit"}</button></div>
      </header>
      <div className="ops-content">
        {step==="today"&&<Today t={t} risks={risks} stock={stock} published={published} ordered={ordered} received={received} closed={closed} go={go}/>}
        {step==="staff"&&<Staff t={t} assigned={assigned} published={published} assign={()=>setAssigned(true)} publish={()=>setPublished(true)}/>}
        {step==="order"&&<Order t={t} stock={stock} ordered={ordered} approve={()=>setOrdered(true)} go={go}/>}
        {step==="delivery"&&<Delivery t={t} ordered={ordered} received={received} receive={()=>setReceived(18)} go={go}/>}
        {step==="count"&&<Count t={t} stock={stock} counted={counted} waste={waste} count={()=>setCounted(true)} addWaste={()=>setWaste(1)} go={go}/>}
        {step==="close"&&<Close t={t} stock={stock} published={published} counted={counted} closed={closed} finish={()=>setClosed(true)} go={go}/>}
        {step==="copilot"&&<Copilot t={t} stock={stock} waste={waste} closed={closed} answer={answer} ask={()=>setAnswer(true)}/>}
      </div>
    </main>
  </div>;
}

type T={ [K in keyof typeof copy.nl]: string };
const tx=(t:T,nl:string,en:string)=>t.lang==="nl"?nl:en;
function Header({t,eyebrow,title,body}:{t:T;eyebrow:string;title:string;body:string}){return <section className="ops-heading"><div><span>{eyebrow}</span><h1>{title}</h1><p>{body}</p></div><div className="live-pill"><i/>{tx(t,"Live demostatus","Live demo state")}</div></section>}
function Today({t,risks,stock,published,ordered,received,closed,go}:{t:T;risks:number;stock:number;published:boolean;ordered:boolean;received:number;closed:boolean;go:(s:Step)=>void}){
  return <><Header t={t} eyebrow={`${t.today} · ${t.date}`} title={t.expected} body={risks?`${risks} ${t.risk}`:t.done}/>
    <section className="ops-brief"><div><span>{t.next}</span><h2>{!published?t.staffRisk:stock<54?t.stockRisk:!closed?tx(t,"Nachtafsluiting wacht op goedkeuring","Night close awaits approval"):t.done}</h2><p>{!published?tx(t,"De vraag vereist zes barmedewerkers; vijf zijn toegewezen. Mila is beschikbaar en gekwalificeerd.","Demand requires six bar staff; five are assigned. Mila is available and qualified."):stock<54?tx(t,`54 flessen vereist · ${stock} beschikbaar. Het advies gebruikt forecast, voorraad en besteleenheid.`,`Required 54 bottles · ${stock} available. The recommendation uses forecast, on-hand and order multiple.`):tx(t,"Alle materiële records zijn gekoppeld aan de handelsdatum.","All material records are linked to the trading date.")}</p></div><button onClick={()=>go(!published?"staff":stock<54?"order":"close")}>{t.review}</button></section>
    <section className="ops-kpis"><article><span>{tx(t,"Verwachte omzet","Expected revenue")}</span><b>€ 18.600</b><small>{tx(t,"620 gasten · gemiddeld €30,00","620 guests · €30.00 average")}</small></article><article><span>{tx(t,"Geplande arbeid","Planned labor")}</span><b>{published?"€ 3.612":"€ 3.348"}</b><small>{published?tx(t,"19,4% · volledig bezet","19.4% · fully staffed"):tx(t,"18,0% · één open rol","18.0% · one open role")}</small></article><article><span>{tx(t,"Vodkavoorraad","Vodka stock")}</span><b>{stock} {tx(t,"flessen","bottles")}</b><small>{tx(t,"54 vereist","54 required")} · {ordered?received?tx(t,"deellevering","partial receipt"):tx(t,"24 besteld","24 ordered"):tx(t,"bestelling niet goedgekeurd","order not approved")}</small></article><article><span>{tx(t,"Afsluitstatus","Close status")}</span><b>{closed?tx(t,"Goedgekeurd","Approved"):"Open"}</b><small>{closed?tx(t,"onveranderlijke snapshot","immutable snapshot"):tx(t,"forecast versus werkelijk wacht","forecast-to-actual pending")}</small></article></section>
    <section className="ops-timeline"><h3>{tx(t,"Operationele tijdlijn","Operating timeline")}</h3>{[
      ["18:00",tx(t,"Teambriefing","Team briefing"),published?tx(t,"Rooster v4 gepubliceerd","Roster v4 published"):tx(t,"Roostertekort","Roster shortage"),"staff"],
      ["20:00",tx(t,"Levervenster","Delivery window"),received?tx(t,"18 flessen ontvangen","18 bottles received"):ordered?tx(t,"Bestelling goedgekeurd","Order approved"):tx(t,"Goedkeuring vereist","Approval required"),"delivery"],
      ["22:00",tx(t,"Deuren open","Doors open"),tx(t,"620 gasten verwacht","620 forecast guests"),"today"],
      ["06:00",tx(t,"Handelsdag afsluiten","Trading-date close"),closed?tx(t,"Goedgekeurd","Approved"):tx(t,"Niet gestart","Not started"),"close"],
    ].map(row=><button key={row[0]} onClick={()=>go(row[3] as Step)}><time>{row[0]}</time><span><b>{row[1]}</b><small>{row[2]}</small></span><em>{tx(t,"Openen","Open")}</em></button>)}</section></>
}
function Staff({t,assigned,published,assign,publish}:{t:T;assigned:boolean;published:boolean;assign:()=>void;publish:()=>void}){return <><Header t={t} eyebrow={tx(t,"Forecast → rooster","Forecast → roster")} title={tx(t,"Vrijdagrooster · 18:00–06:00","Friday roster · 18:00–06:00")} body={tx(t,"Vereiste bezetting, beschikbaarheid, kwalificaties en loonkosten in één beslissing.","Required staffing, availability, qualifications and labor cost in one decision.")}/><section className="roster-summary"><b>6 {tx(t,"vereist","required")}</b><b>{assigned?6:5} {tx(t,"toegewezen","assigned")}</b><b>{published?0:1} open</b><b>{published?"€ 3.612":"€ 3.348"}</b></section><section className="week-board"><header><span>{tx(t,"Rol","Role")}</span><span>18</span><span>20</span><span>22</span><span>00</span><span>02</span><span>04</span><span>06</span></header><div><b>Bar lead</b><i className="shift lead">Noah · 20–05</i></div><div><b>Bartenders</b><i className="shift">Lena · 21–05</i><i className="shift second">Jules · 22–06</i></div><div><b>{tx(t,"Open rol","Open role")}</b><button className={`shift open ${assigned?"filled":""}`} onClick={assign}>{assigned?"Mila · 23–05":"Open · 23–05"}</button></div></section><section className="candidate-drawer"><div><span>{tx(t,"Beste geschikte kandidaat","Best eligible match")}</span><h3>Mila de Boer</h3><p>{tx(t,"Beschikbaar · Bar gekwalificeerd · geen overlap · 11 uur rust · +€264 arbeid.","Available · Bar qualified · no overlap · 11h rest · +€264 labor.")}</p></div><button disabled={assigned} onClick={assign}>{assigned?t.done:t.assign}</button><button disabled={!assigned||published} onClick={publish}>{published?t.done:t.publish}</button></section></>}
function Order({t,stock,ordered,approve,go}:{t:T;stock:number;ordered:boolean;approve:()=>void;go:(s:Step)=>void}){const shortage=Math.max(0,54-stock);return <><Header t={t} eyebrow={tx(t,"Forecast → verwacht verbruik → bestelling","Forecast → expected usage → order")} title={tx(t,"Deterministisch besteladvies","Deterministic order recommendation")} body={tx(t,"Geen AI-gok: forecastverbruik, voorraad, veiligheidsniveau en besteleenheid.","No AI guess: forecast usage, on-hand stock, safety level and supplier order multiple.")}/><section className="calc-strip"><span><b>54</b> {tx(t,"vereist","required")}</span><i>−</i><span><b>{stock}</b> {tx(t,"voorraad","on hand")}</span><i>+</i><span><b>6</b> {tx(t,"veiligheid","safety")}</span><i>=</i><span><b>{shortage+6}</b> {tx(t,"netto nodig","net need")}</span><i>→</i><span><b>24</b> {tx(t,"afgeronde bestelling","rounded order")}</span></section><section className="purchase-card"><div><span>North Sea Spirits</span><h2>Vodka house 1L</h2><p>{tx(t,"24 flessen · besteleenheid 6 · €18,40 netto per stuk","24 bottles · order multiple 6 · €18.40 net each")}</p></div><strong>€ 441,60</strong><button disabled={ordered} onClick={approve}>{ordered?t.done:t.approve}</button>{ordered?<button className="secondary" onClick={()=>go("delivery")}>{t.delivery}</button>:null}</section></>}
function Delivery({t,ordered,received,receive,go}:{t:T;ordered:boolean;received:number;receive:()=>void;go:(s:Step)=>void}){return <><Header t={t} eyebrow={tx(t,"Inkooporder → voorraadboek","Purchase order → stock ledger")} title={tx(t,"Ontvang PO-2026-0731","Receive PO-2026-0731")} body={tx(t,"Een deellevering boekt één idempotente voorraadmutatie; het restant blijft open.","Partial receipt posts one idempotent stock movement; the remaining quantity stays open.")}/><section className="receive-card"><div><b>Vodka house 1L</b><span>{tx(t,"Besteld","Ordered")} 24 · {tx(t,"ontvangen","received")} {received} · {tx(t,"resterend","remaining")} {24-received}</span></div><label>{tx(t,"Beschadigd","Damaged")}<input value="0" readOnly/></label><button disabled={!ordered||received>0} onClick={receive}>{received?t.done:t.receive}</button></section>{!ordered?<p className="gate-message">{tx(t,"Keur eerst de inkooporder goed.","Approve the purchase order first.")}</p>:received?<section className="success-state"><b>{tx(t,"Voorraadmutatie geboekt","Stock movement posted")}</b><p>{tx(t,"+18 flessen · Hoofdbar · referentie PO-2026-0731 · ontvangst blijft gedeeltelijk.","+18 bottles · Main bar · reference PO-2026-0731 · receipt remains partial.")}</p><button onClick={()=>go("count")}>{t.count}</button></section>:null}</>}
function Count({t,stock,counted,waste,count,addWaste,go}:{t:T;stock:number;counted:boolean;waste:number;count:()=>void;addWaste:()=>void;go:(s:Step)=>void}){return <><Header t={t} eyebrow={tx(t,"Mobiele telling · Hoofdbar","Mobile count · Main bar")} title={tx(t,"Snelle voorraadtelling","Fast stock count")} body={tx(t,"Verpakkingen en losse eenheden worden transparant omgerekend en in deze demosessie bewaard.","Packages and loose units are converted transparently and kept in this demo session.")}/><section className="count-sheet"><div><span>Product</span><span>{tx(t,"Verwacht","Expected")}</span><span>{tx(t,"Volle flessen","Full bottles")}</span><span>{tx(t,"Verschil","Variance")}</span></div><div><b>Vodka house 1L</b><span>{stock}</span><input aria-label={tx(t,"Getelde flessen","Counted bottles")} defaultValue={stock}/><em>{counted?"0":tx(t,"Concept","Draft")}</em></div><div><b>Premium gin 70cl</b><span>16</span><input aria-label={tx(t,"Getelde gin","Counted gin")} defaultValue="16"/><em>{counted?"0":tx(t,"Concept","Draft")}</em></div></section><section className="count-actions"><button disabled={counted} onClick={count}>{counted?t.done:t.saveCount}</button><button disabled={!counted||waste>0} onClick={addWaste}>{waste?t.done:t.recordWaste}</button>{waste?<button className="secondary" onClick={()=>go("close")}>{t.close}</button>:null}</section></>}
function Close({t,stock,published,counted,closed,finish,go}:{t:T;stock:number;published:boolean;counted:boolean;closed:boolean;finish:()=>void;go:(s:Step)=>void}){return <><Header t={t} eyebrow={tx(t,"Afsluiten → winst → leren","Close → profit → learning")} title={tx(t,"Handelsdag afsluiten","Trading date close")} body={tx(t,"Forecast, arbeid, voorraad en betaalbewijs worden afgestemd vóór een onveranderlijke goedkeuringssnapshot.","Forecast, labor, stock and payment evidence are reconciled before an immutable approval snapshot.")}/><section className="close-grid"><article><span>{tx(t,"Forecastomzet","Forecast revenue")}</span><b>€ 18.600</b><small>{tx(t,"Werkelijk","Actual")} €18.240 · −€360</small></article><article><span>{tx(t,"Arbeid","Labor")}</span><b>{published?"€ 3.684":tx(t,"Onvolledig","Incomplete")}</b><small>{tx(t,"Gepland","Planned")} €3.612 · +€72</small></article><article><span>{tx(t,"Drankverbruik","Beverage usage")}</span><b>{counted?`${stock} ${tx(t,"geteld","counted")}`:tx(t,"Telling ontbreekt","Count missing")}</b><small>{tx(t,"Theoretisch verschil","Theoretical variance")} €184</small></article><article><span>{tx(t,"Bijdrage","Contribution")}</span><b>€ 5.126</b><small>28,1% · {tx(t,"doel","target")} 31,0%</small></article></section><section className="approval-bar"><p>{!published?tx(t,"Publiceer eerst het rooster.","Publish the roster first."):!counted?tx(t,"Dien eerst de telling in.","Submit the stock count first."):tx(t,"Alle vereiste bewijs is aanwezig.","All required evidence is present.")}</p><button disabled={!published||!counted||closed} onClick={finish}>{closed?t.done:t.finish}</button>{closed?<button className="secondary" onClick={()=>go("copilot")}>{t.copilot}</button>:null}</section></>}
function Copilot({t,stock,waste,closed,answer,ask}:{t:T;stock:number;waste:number;closed:boolean;answer:boolean;ask:()=>void}){return <><Header t={t} eyebrow={tx(t,"Bewijsgekoppelde deterministische copilot","Evidence-linked deterministic copilot")} title={tx(t,"Vraag NightProfit","Ask NightProfit")} body={tx(t,"Feiten en berekeningen blijven deterministisch; materiële wijzigingen vereisen altijd goedkeuring.","Facts and calculations remain deterministic; material changes always require approval.")}/><section className="copilot-layout"><div className="suggestions"><span>{tx(t,"Voorgestelde vraag","Suggested question")}</span><button onClick={ask}>{t.ask}</button><button onClick={ask}>{tx(t,"Welke actie heeft de hoogste waarde?","Which action has the highest value?")}</button></div><div className="answer-panel">{!answer?<div className="empty-answer"><b>{tx(t,"Kies een vraag","Choose a question")}</b><p>{tx(t,"De copilot gebruikt de huidige vestiging, handelsdatum en jouw rechten.","The copilot uses the current venue, trading date and your permissions.")}</p></div>:<><span>{tx(t,"FEITEN","FACTS")} · {t.evidence}</span><h2>{tx(t,"De marge daalde 2,9 procentpunt.","Margin fell 2.9 percentage points.")}</h2><p>{tx(t,`De omzet eindigde €360 onder forecast, arbeid €72 boven plan en drankverschil droeg €184 bij. ${waste?`Eén geregistreerde gebroken fles is meegenomen; ${stock} flessen resteren.`:"Geen verspillingsrecord verklaart het volledige voorraadverschil."}`,`Revenue finished €360 below forecast, labor cost €72 above plan and beverage variance contributed €184. ${waste?`One recorded broken bottle is included; ${stock} bottles remain.`:"No waste record explains the full stock variance."}`)}</p><ul><li>{tx(t,"Forecastsnapshot","Forecast snapshot")} · 31 July</li><li>{tx(t,"Roosterversie","Roster version")} 4 · {closed?tx(t,"goedgekeurde afsluiting","approved close"):tx(t,"afsluiting niet goedgekeurd","close not approved")}</li><li>{tx(t,"Voorraadtelling · Hoofdbar","Stock count · Main bar")}</li></ul></>}</div></section></>}
