"use client";

import { useMemo, useState, type DragEvent } from "react";
import { useRouter } from "next/navigation";
import { useAuthLocale } from "./auth-locale";

type Venue={id:string;name:string};
type Department={id:string;venue_id:string;name:string};
type Role={id:string;department_id:string;name:string;hourly_cost_minor:string;minimum_staff:number;guests_per_staff:number};
type Staff={id:string;full_name:string;role_name:string;onboarding_status?:string;contact_email?:string|null};
type Interval={id:string;venue_id:string;starts_at:string;ends_at:string;expected_guests:number;expected_revenue_minor:string;required_staff:number};
type Shift={id:string;venue_id:string;department_id:string;role_id:string;staff_id:string|null;starts_at:string;ends_at:string;break_minutes:number;hourly_cost_minor:string;status:string};
type Absence={id:string;venue_id:string;staff_id:string;starts_at:string;ends_at:string;absence_type:string;status:string;note:string|null};

const dayMs=86400000;
const isoLocal=(date:Date)=>{const offset=date.getTimezoneOffset()*60000;return new Date(date.getTime()-offset).toISOString().slice(0,16)};
const monday=(value:Date)=>{const date=new Date(value);date.setHours(0,0,0,0);date.setDate(date.getDate()-((date.getDay()+6)%7));return date};

export function RosterBoard({organisationId,venues,departments,roles,staff,intervals,initialShifts,absences}:{organisationId:string;venues:Venue[];departments:Department[];roles:Role[];staff:Staff[];intervals:Interval[];initialShifts:Shift[];absences:Absence[]}){
  const {locale}=useAuthLocale(),router=useRouter();
  const tx=(nl:string,en:string)=>locale==="nl"?nl:en;
  const [venueId,setVenueId]=useState(venues[0]?.id??"");
  const [weekStart,setWeekStart]=useState(()=>monday(new Date()));
  const [shifts,setShifts]=useState(initialShifts);
  const [selected,setSelected]=useState<Shift|null>(null);
  const [panel,setPanel]=useState<"shift"|"new"|"team"|"absence"|null>(null);
  const [newShift,setNewShift]=useState<{day:Date;departmentId:string;staffId:string}|null>(null);
  const [busy,setBusy]=useState(false),[message,setMessage]=useState("");
  const days=useMemo(()=>Array.from({length:7},(_,index)=>new Date(weekStart.getTime()+index*dayMs)),[weekStart]);
  const weekEnd=new Date(weekStart.getTime()+7*dayMs);
  const visibleShifts=shifts.filter(row=>row.venue_id===venueId&&new Date(row.starts_at)>=weekStart&&new Date(row.starts_at)<weekEnd&&row.status!=="cancelled");
  const visibleIntervals=intervals.filter(row=>row.venue_id===venueId&&new Date(row.starts_at)>=weekStart&&new Date(row.starts_at)<weekEnd);
  const venueDepartments=departments.filter(row=>row.venue_id===venueId);
  const activeStaff=staff.filter(row=>row.onboarding_status!=="suspended");
  const revenue=visibleIntervals.reduce((sum,row)=>sum+BigInt(row.expected_revenue_minor),0n);
  const labor=visibleShifts.reduce((sum,row)=>{const minutes=Math.max(0,Math.floor((new Date(row.ends_at).getTime()-new Date(row.starts_at).getTime())/60000)-row.break_minutes);return sum+(BigInt(row.hourly_cost_minor)*BigInt(minutes)+30n)/60n},0n);
  const currency=(minor:bigint)=>new Intl.NumberFormat(locale==="nl"?"nl-NL":"en-GB",{style:"currency",currency:"EUR",maximumFractionDigits:0}).format(Number(minor)/100);
  const percent=revenue?`${Number(labor*10000n/revenue)/100}%`:"—";

  async function mutate(action:string,values:Record<string,string>,optimistic?:()=>void){
    setBusy(true);setMessage("");
    try{const response=await fetch("/api/planning",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({organisationId,locale:locale==="nl"?"nl-NL":"en-US",action,values})});const result=await response.json() as {message?:string;errorCode?:string};if(!response.ok)throw new Error(result.errorCode==="SHIFT_OVERLAP"?tx("Deze medewerker heeft al een overlappende dienst.","This employee already has an overlapping shift."):tx("De wijziging kon niet worden opgeslagen.","The change could not be saved."));optimistic?.();setMessage(result.message??tx("Opgeslagen.","Saved."));router.refresh();}
    catch(error){setMessage(error instanceof Error?error.message:tx("Opslaan mislukt.","Save failed."));}finally{setBusy(false)}
  }
  const shiftValues=(row:Shift)=>({venueId:row.venue_id,shiftId:row.id,departmentId:row.department_id,roleId:row.role_id,staffId:row.staff_id??"open",startsAt:isoLocal(new Date(row.starts_at)),endsAt:isoLocal(new Date(row.ends_at)),breakMinutes:String(row.break_minutes),hourlyCost:(Number(BigInt(row.hourly_cost_minor))/100).toFixed(2)});
  function moveShift(row:Shift,targetDay:Date){const start=new Date(row.starts_at),end=new Date(row.ends_at),duration=end.getTime()-start.getTime();const nextStart=new Date(targetDay);nextStart.setHours(start.getHours(),start.getMinutes());const next={...row,starts_at:nextStart.toISOString(),ends_at:new Date(nextStart.getTime()+duration).toISOString(),status:"draft"};void mutate("shift_update",shiftValues(next),()=>setShifts(current=>current.map(item=>item.id===row.id?next:item)));}
  function drop(event:DragEvent,targetDay:Date){event.preventDefault();const row=shifts.find(item=>item.id===event.dataTransfer.getData("text/shift-id"));if(row)moveShift(row,targetDay)}
  function resize(row:Shift,minutes:number){const next={...row,ends_at:new Date(new Date(row.ends_at).getTime()+minutes*60000).toISOString(),status:"draft"};if(new Date(next.ends_at)<=new Date(next.starts_at))return;void mutate("shift_update",shiftValues(next),()=>{setShifts(current=>current.map(item=>item.id===row.id?next:item));setSelected(next)})}
  const coverage=days.map(day=>{const end=new Date(day.getTime()+dayMs);const required=visibleIntervals.filter(row=>new Date(row.starts_at)>=day&&new Date(row.starts_at)<end).reduce((max,row)=>Math.max(max,row.required_staff),0);const planned=visibleShifts.filter(row=>new Date(row.starts_at)>=day&&new Date(row.starts_at)<end).length;return{required,planned}});

  return <div className="roster-product">
    <header className="roster-toolbar">
      <div><span className="eyebrow">{tx("TEAM & ROOSTER","TEAM & ROSTER")}</span><h2>{tx("Weekrooster","Weekly roster")}</h2><p>{tx("Vraag, beschikbaarheid en loonkosten in één werkvlak.","Demand, availability and labor cost in one workspace.")}</p></div>
      <div className="roster-actions"><button className="secondary" onClick={()=>setPanel("team")}>{tx("Team beheren","Manage team")}</button><button className="primary" disabled={busy||!venueId} onClick={()=>{if(!departments.length||!roles.length||!staff.length){setPanel("team");return}void mutate("proposal",{venueId,tradingDate:days[0].toISOString().slice(0,10)})}}>{tx("Maak rooster","Build roster")}</button><button className="primary publish" disabled={busy||!visibleShifts.some(row=>row.status==="draft")} onClick={()=>void mutate("publish",{venueId,startsAt:isoLocal(weekStart),endsAt:isoLocal(weekEnd)})}>{tx("Publiceer","Publish")}</button></div>
    </header>
    <section className="roster-context" aria-label={tx("Roosterperiode","Roster period")}>
      <label>{tx("Vestiging","Venue")}<select value={venueId} onChange={event=>setVenueId(event.target.value)}>{venues.map(row=><option key={row.id} value={row.id}>{row.name}</option>)}</select></label>
      <div className="week-switch"><button aria-label={tx("Vorige week","Previous week")} onClick={()=>setWeekStart(new Date(weekStart.getTime()-7*dayMs))}>←</button><strong>{weekStart.toLocaleDateString(locale==="nl"?"nl-NL":"en-GB",{day:"numeric",month:"short"})} – {new Date(weekEnd.getTime()-dayMs).toLocaleDateString(locale==="nl"?"nl-NL":"en-GB",{day:"numeric",month:"short",year:"numeric"})}</strong><button aria-label={tx("Volgende week","Next week")} onClick={()=>setWeekStart(new Date(weekStart.getTime()+7*dayMs))}>→</button></div>
      <button className="secondary" disabled={busy} onClick={()=>void mutate("copy_week",{venueId,startsAt:isoLocal(new Date(weekStart.getTime()-7*dayMs)),endsAt:isoLocal(weekStart),idempotencyKey:crypto.randomUUID()})}>{tx("Vorige week kopiëren","Copy previous week")}</button>
      <button className="secondary" onClick={()=>setPanel("absence")}>{tx("Verlof / ziek","Leave / sickness")}</button>
    </section>
    <section className="roster-kpis">
      <article><span>{tx("Omzetforecast","Revenue forecast")}</span><b>{currency(revenue)}</b><small>{visibleIntervals.length} {tx("vraagblokken","demand intervals")}</small></article>
      <article><span>{tx("Geplande loonkosten","Planned labor")}</span><b>{currency(labor)}</b><small>{percent} {tx("van omzet","of revenue")}</small></article>
      <article><span>{tx("Dekking","Coverage")}</span><b>{coverage.filter(row=>row.planned>=row.required).length}/7</b><small>{tx("dagen op norm","days on target")}</small></article>
      <article><span>{tx("Open diensten","Open shifts")}</span><b>{visibleShifts.filter(row=>!row.staff_id).length}</b><small>{tx("toewijzing nodig","need assignment")}</small></article>
    </section>
    {message?<div className="roster-message" role="status">{message}</div>:null}
    {!venueDepartments.length||!roles.length?<button className="guided-setup" onClick={()=>setPanel("team")}><b>{tx("Rooster instellen","Set up roster")}</b><span>{tx("Voeg in één stap een afdeling, rol en eerste medewerker toe.","Add a department, role and first employee in one guided step.")}</span><em>→</em></button>:null}
    <section className="roster-board" aria-label={tx("Visueel weekrooster","Visual weekly roster")}>
      <div className="roster-grid roster-head"><div className="employee-heading">{tx("Medewerker","Employee")}</div>{days.map((day,index)=><div key={day.toISOString()} className={coverage[index].planned<coverage[index].required?"coverage-gap":""}><b>{day.toLocaleDateString(locale==="nl"?"nl-NL":"en-GB",{weekday:"short"})}</b><span>{day.getDate()}</span><small>{coverage[index].planned}/{coverage[index].required} {tx("bezet","staffed")}</small></div>)}</div>
      {venueDepartments.map(department=><div className="department-group" key={department.id}><h3>{department.name}</h3>{[...activeStaff,{id:"open",full_name:tx("Open diensten","Open shifts"),role_name:"",onboarding_status:"cleared"}].map(person=><div className="roster-grid roster-row" key={`${department.id}-${person.id}`}><div className="employee-cell"><span className="avatar">{person.id==="open"?"+":person.full_name.slice(0,2).toUpperCase()}</span><div><b>{person.full_name}</b><small>{person.role_name}</small></div></div>{days.map(day=>{const cell=visibleShifts.filter(row=>row.department_id===department.id&&(person.id==="open"?!row.staff_id:row.staff_id===person.id)&&new Date(row.starts_at).toDateString()===day.toDateString());const dayAbsence=person.id!=="open"&&absences.find(row=>row.staff_id===person.id&&row.status!=="rejected"&&new Date(row.starts_at)<new Date(day.getTime()+dayMs)&&new Date(row.ends_at)>day);return <div className={`shift-cell ${dayAbsence?"unavailable":""}`} key={day.toISOString()} onDragOver={event=>event.preventDefault()} onDrop={event=>drop(event,day)}>{dayAbsence?<span className="absence-chip">{dayAbsence.absence_type==="sickness"?tx("Ziek","Sick"):tx("Verlof","Leave")}</span>:null}{cell.map(row=><button draggable onDragStart={event=>event.dataTransfer.setData("text/shift-id",row.id)} onClick={()=>{setSelected(row);setPanel("shift")}} className={`shift-card ${row.status}`} key={row.id}><b>{roles.find(role=>role.id===row.role_id)?.name??tx("Dienst","Shift")}</b><span>{new Date(row.starts_at).toLocaleTimeString(locale==="nl"?"nl-NL":"en-GB",{hour:"2-digit",minute:"2-digit"})}–{new Date(row.ends_at).toLocaleTimeString(locale==="nl"?"nl-NL":"en-GB",{hour:"2-digit",minute:"2-digit"})}</span><small>{row.break_minutes?`${row.break_minutes}m ${tx("pauze","break")}`:""}</small></button>)}{!dayAbsence?<button className="add-shift" aria-label={`${tx("Dienst toevoegen","Add shift")} ${person.full_name}`} onClick={()=>{setNewShift({day,departmentId:department.id,staffId:person.id});setPanel("new")}}>＋</button>:null}</div>})}</div>)}</div>)}
    </section>
    {panel?<div className="side-panel-backdrop" onClick={()=>setPanel(null)}><aside className="roster-side-panel" onClick={event=>event.stopPropagation()} aria-label={tx("Contextpaneel","Context panel")}><button className="panel-close" onClick={()=>setPanel(null)} aria-label={tx("Sluiten","Close")}>×</button>{panel==="shift"&&selected?<ShiftEditor row={selected} departments={venueDepartments} roles={roles} staff={activeStaff} locale={locale} busy={busy} save={values=>void mutate("shift_update",values,()=>setShifts(current=>current.map(item=>item.id===selected.id?{...selected,starts_at:new Date(values.startsAt).toISOString(),ends_at:new Date(values.endsAt).toISOString(),staff_id:values.staffId==="open"?null:values.staffId,role_id:values.roleId,department_id:values.departmentId,break_minutes:Number(values.breakMinutes),hourly_cost_minor:String(Math.round(Number(values.hourlyCost)*100)),status:"draft"}:item)))} resize={minutes=>resize(selected,minutes)} cancel={()=>void mutate("shift_cancel",{venueId:selected.venue_id,shiftId:selected.id},()=>{setShifts(current=>current.filter(item=>item.id!==selected.id));setPanel(null)})}/>:panel==="new"&&newShift?<NewShiftEditor venueId={venueId} draft={newShift} departments={venueDepartments} roles={roles} staff={activeStaff} locale={locale} busy={busy} save={values=>void mutate("shift",values,()=>{setPanel(null);router.refresh()})}/>:panel==="team"?<TeamSetup organisationId={organisationId} venueId={venueId} departments={venueDepartments} roles={roles} staff={activeStaff} busy={busy} mutate={mutate} tx={tx}/>:<AbsencePanel venueId={venueId} staff={activeStaff} absences={absences} busy={busy} mutate={mutate} tx={tx}/>}</aside></div>:null}
  </div>
}

function NewShiftEditor({venueId,draft,departments,roles,staff,locale,busy,save}:{venueId:string;draft:{day:Date;departmentId:string;staffId:string};departments:Department[];roles:Role[];staff:Staff[];locale:string;busy:boolean;save:(values:Record<string,string>)=>void}){const tx=(nl:string,en:string)=>locale==="nl"?nl:en;const start=new Date(draft.day);start.setHours(17,0,0,0);const end=new Date(draft.day);end.setHours(23,0,0,0);return <form onSubmit={event=>{event.preventDefault();save(Object.fromEntries(new FormData(event.currentTarget)) as Record<string,string>)}}><h3>{tx("Dienst toevoegen","Add shift")}</h3><input type="hidden" name="venueId" value={venueId}/><label>{tx("Medewerker","Employee")}<select name="staffId" defaultValue={draft.staffId}><option value="open">{tx("Open dienst","Open shift")}</option>{staff.map(person=><option key={person.id} value={person.id}>{person.full_name}</option>)}</select></label><label>{tx("Afdeling","Department")}<select name="departmentId" defaultValue={draft.departmentId}>{departments.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>{tx("Rol","Role")}<select name="roleId" defaultValue={roles.find(item=>item.department_id===draft.departmentId)?.id}>{roles.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>{tx("Start","Start")}<input name="startsAt" type="datetime-local" defaultValue={isoLocal(start)} required/></label><label>{tx("Einde","End")}<input name="endsAt" type="datetime-local" defaultValue={isoLocal(end)} required/></label><label>{tx("Pauze (min)","Break (min)")}<input name="breakMinutes" type="number" min="0" max="480" defaultValue="30"/></label><label>{tx("All-in uurkosten (€)","All-in hourly cost (€)")}<input name="hourlyCost" inputMode="decimal" defaultValue={(Number(BigInt(roles.find(item=>item.department_id===draft.departmentId)?.hourly_cost_minor??"0"))/100).toFixed(2)} required/></label><button className="primary" disabled={busy}>{tx("Conceptdienst opslaan","Save draft shift")}</button></form>}

function ShiftEditor({row,departments,roles,staff,locale,busy,save,resize,cancel}:{row:Shift;departments:Department[];roles:Role[];staff:Staff[];locale:string;busy:boolean;save:(values:Record<string,string>)=>void;resize:(minutes:number)=>void;cancel:()=>void}){const tx=(nl:string,en:string)=>locale==="nl"?nl:en;return <form onSubmit={event=>{event.preventDefault();save(Object.fromEntries(new FormData(event.currentTarget)) as Record<string,string>)}}><h3>{tx("Dienst bewerken","Edit shift")}</h3><input type="hidden" name="venueId" value={row.venue_id}/><input type="hidden" name="shiftId" value={row.id}/><label>{tx("Medewerker","Employee")}<select name="staffId" defaultValue={row.staff_id??"open"}><option value="open">{tx("Open dienst","Open shift")}</option>{staff.map(person=><option key={person.id} value={person.id}>{person.full_name}</option>)}</select></label><label>{tx("Afdeling","Department")}<select name="departmentId" defaultValue={row.department_id}>{departments.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>{tx("Rol","Role")}<select name="roleId" defaultValue={row.role_id}>{roles.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>{tx("Start","Start")}<input name="startsAt" type="datetime-local" defaultValue={isoLocal(new Date(row.starts_at))}/></label><label>{tx("Einde","End")}<input name="endsAt" type="datetime-local" defaultValue={isoLocal(new Date(row.ends_at))}/></label><label>{tx("Pauze (min)","Break (min)")}<input name="breakMinutes" type="number" min="0" max="480" defaultValue={row.break_minutes}/></label><label>{tx("All-in uurkosten (€)","All-in hourly cost (€)")}<input name="hourlyCost" inputMode="decimal" defaultValue={(Number(BigInt(row.hourly_cost_minor))/100).toFixed(2)}/></label><div className="resize-actions"><button type="button" onClick={()=>resize(-30)}>−30m</button><button type="button" onClick={()=>resize(30)}>+30m</button></div><button className="primary" disabled={busy}>{tx("Opslaan","Save")}</button><button className="danger" type="button" disabled={busy} onClick={cancel}>{tx("Dienst verwijderen","Delete shift")}</button></form>}

function TeamSetup({venueId,departments,roles,staff,busy,mutate,tx}:{organisationId:string;venueId:string;departments:Department[];roles:Role[];staff:Staff[];busy:boolean;mutate:(action:string,values:Record<string,string>)=>Promise<void>;tx:(nl:string,en:string)=>string}){return <div><h3>{tx("Team instellen","Set up team")}</h3>{!departments.length?<form onSubmit={event=>{event.preventDefault();void mutate("department",Object.fromEntries(new FormData(event.currentTarget)) as Record<string,string>)}}><input type="hidden" name="venueId" value={venueId}/><label>{tx("Eerste afdeling","First department")}<input name="name" required placeholder={tx("Bar, keuken, bediening…","Bar, kitchen, floor…")}/></label><button className="primary" disabled={busy}>{tx("Afdeling toevoegen","Add department")}</button></form>:!roles.length?<form onSubmit={event=>{event.preventDefault();void mutate("role",Object.fromEntries(new FormData(event.currentTarget)) as Record<string,string>)}}><label>{tx("Afdeling","Department")}<select name="departmentId">{departments.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>{tx("Rolnaam","Role name")}<input name="name" required/></label><label>{tx("Uurkosten (€)","Hourly cost (€)")}<input name="hourlyCost" defaultValue="18.50" required/></label><input type="hidden" name="minimumStaff" value="1"/><input type="hidden" name="guestsPerStaff" value="30"/><button className="primary" disabled={busy}>{tx("Rol toevoegen","Add role")}</button></form>:<form onSubmit={event=>{event.preventDefault();void mutate("staff",Object.fromEntries(new FormData(event.currentTarget)) as Record<string,string>)}}><input type="hidden" name="venueId" value={venueId}/><label>{tx("Naam","Name")}<input name="fullName" required/></label><label>{tx("E-mail","Email")}<input name="email" type="email"/></label><label>{tx("Telefoon","Phone")}<input name="phone" type="tel"/></label><label>{tx("Functie","Role")}<input name="roleName" required defaultValue={roles[0]?.name}/></label><label>{tx("Contract","Contract")}<select name="engagementType"><option value="employee">{tx("Medewerker","Employee")}</option><option value="contractor">{tx("Zelfstandige","Contractor")}</option><option value="temporary">{tx("Tijdelijk","Temporary")}</option></select></label><label>{tx("Taal","Language")}<select name="preferredLanguage"><option value="nl">NL</option><option value="en">EN</option></select></label><button className="primary" disabled={busy}>{tx("Medewerker toevoegen","Add employee")}</button></form>}<div className="team-list">{staff.map(person=><div key={person.id}><span className="avatar">{person.full_name.slice(0,2).toUpperCase()}</span><div><b>{person.full_name}</b><small>{person.role_name}</small></div><button disabled={busy} onClick={()=>void mutate("staff_deactivate",{staffId:person.id})}>{tx("Deactiveer","Deactivate")}</button></div>)}</div></div>}

function AbsencePanel({venueId,staff,absences,busy,mutate,tx}:{venueId:string;staff:Staff[];absences:Absence[];busy:boolean;mutate:(action:string,values:Record<string,string>)=>Promise<void>;tx:(nl:string,en:string)=>string}){return <div><h3>{tx("Verlof en ziekte","Leave and sickness")}</h3><form onSubmit={event=>{event.preventDefault();void mutate("absence",Object.fromEntries(new FormData(event.currentTarget)) as Record<string,string>)}}><input type="hidden" name="venueId" value={venueId}/><label>{tx("Medewerker","Employee")}<select name="staffId">{staff.map(person=><option key={person.id} value={person.id}>{person.full_name}</option>)}</select></label><label>{tx("Type","Type")}<select name="absenceType"><option value="leave">{tx("Verlof","Leave")}</option><option value="sickness">{tx("Ziek","Sickness")}</option><option value="other">{tx("Overig","Other")}</option></select></label><label>{tx("Start","Start")}<input name="startsAt" type="datetime-local" required/></label><label>{tx("Einde","End")}<input name="endsAt" type="datetime-local" required/></label><label>{tx("Toelichting","Note")}<textarea name="note"/></label><button className="primary" disabled={busy}>{tx("Opslaan","Save")}</button></form><div className="team-list">{absences.filter(row=>row.venue_id===venueId).map(row=><div key={row.id}><div><b>{staff.find(person=>person.id===row.staff_id)?.full_name}</b><small>{row.absence_type} · {row.status}</small></div>{row.status==="requested"?<span><button onClick={()=>void mutate("absence_decide",{venueId,absenceId:row.id,decision:"approved"})}>{tx("Goedkeuren","Approve")}</button><button onClick={()=>void mutate("absence_decide",{venueId,absenceId:row.id,decision:"rejected"})}>{tx("Afwijzen","Reject")}</button></span>:null}</div>)}</div></div>}
