"use client";

import Link from "next/link";
import { useRouter } from "next/navigation";
import { useState } from "react";
import { useAuthLocale } from "./auth-locale";

type Operation={id:string;venue_id:string;service_date:string;stage:string;status:string;demand_snapshot:Record<string,unknown>;staffing_snapshot:Record<string,unknown>;inventory_snapshot:Record<string,unknown>;readiness_checks:Array<Record<string,unknown>>;missing_evidence:string[];stale_reasons:string[]};
type Action={id:string;title:string;rationale:string;why_it_matters:string|null;recommended_response:string|null;severity:string;status:string;due_at:string|null;expected_impact_minor:string|null;evidence_completeness_basis_points:number;rank_score:string;action_type:string};
type Venue={id:string;name:string};

const stages=["prepare","open","run","close","learn"] as const;
export function ServiceAutopilot({organisationId,venues,initialOperation,actions}:{organisationId:string;venues:Venue[];initialOperation:Operation|null;actions:Action[]}){
  const {locale}=useAuthLocale(),router=useRouter(),tx=(nl:string,en:string)=>locale==="nl"?nl:en;
  const [venueId,setVenueId]=useState(initialOperation?.venue_id??venues[0]?.id??"");
  const [serviceDate,setServiceDate]=useState(initialOperation?.service_date??new Date().toISOString().slice(0,10));
  const [busy,setBusy]=useState(false),[message,setMessage]=useState("");
  const op=initialOperation;
  const demand=op?.demand_snapshot??{},staffing=op?.staffing_snapshot??{},inventory=op?.inventory_snapshot??{};
  const money=(minor:unknown)=>new Intl.NumberFormat(locale==="nl"?"nl-NL":"en-GB",{style:"currency",currency:"EUR",maximumFractionDigits:0}).format(Number(minor??0)/100);
  async function mutate(payload:Record<string,string>){setBusy(true);setMessage("");try{const response=await fetch("/api/service-operations",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({organisationId,venueId,...payload})});const result=await response.json() as {message?:string};if(!response.ok)throw new Error(tx("De actie kon niet worden voltooid.","The action could not be completed."));setMessage(result.message??tx("Opgeslagen.","Saved."));router.refresh()}catch(error){setMessage(error instanceof Error?error.message:tx("Opslaan mislukt.","Save failed."))}finally{setBusy(false)}}
  const risk=actions.reduce((sum,row)=>sum+Math.abs(Number(BigInt(row.expected_impact_minor??"0"))),0);
  return <div className="autopilot">
    <header className="autopilot-hero"><div><span className="eyebrow">SERVICE AUTOPILOT</span><h2>{tx("Eén plan voor de hele service","One plan for the whole service")}</h2><p>{tx("Vraag, team, voorraad, inkoop en resultaat delen dezelfde versie en bewijsvoering.","Demand, team, inventory, purchasing and outcome share one version and evidence trail.")}</p></div><div className="autopilot-context"><select aria-label={tx("Vestiging","Venue")} value={venueId} onChange={event=>setVenueId(event.target.value)}>{venues.map(v=><option key={v.id} value={v.id}>{v.name}</option>)}</select><input aria-label={tx("Servicedatum","Service date")} type="date" value={serviceDate} onChange={event=>setServiceDate(event.target.value)}/><button className="primary" disabled={busy||!venueId} onClick={()=>void mutate({action:"prepare",serviceDate})}>{op?tx("Plan vernieuwen","Refresh plan"):tx("Serviceplan maken","Build service plan")}</button></div></header>
    <nav className="service-rhythm" aria-label={tx("Servicefasen","Service stages")}>{stages.map(stage=><span key={stage} className={op?.stage===stage?"active":""}>{tx({prepare:"Voorbereiden",open:"Openen",run:"Service",close:"Afsluiten",learn:"Leren"}[stage],{prepare:"Prepare",open:"Open",run:"Run service",close:"Close",learn:"Learn"}[stage])}</span>)}</nav>
    {message?<p className="autopilot-message" role="status">{message}</p>:null}
    {!op?<section className="autopilot-empty"><h3>{tx("Nog geen gedeeld serviceplan","No shared service plan yet")}</h3><p>{tx("NightProfit bouwt het plan uitsluitend uit opgeslagen operationele feiten en markeert ontbrekend bewijs.","NightProfit builds the plan only from persisted operational facts and marks missing evidence.")}</p></section>:<>
      <section className="decision-package"><div><span>{tx("Verwachte gasten","Expected guests")}</span><b>{String(demand.expected_guests??0)}</b></div><div><span>{tx("Omzetforecast","Revenue forecast")}</span><b>{money(demand.expected_revenue_minor)}</b></div><div><span>{tx("Geplande diensten","Planned shifts")}</span><b>{String(staffing.shift_count??0)}</b></div><div><span>{tx("Loonbudget","Labor budget")}</span><b>{money(staffing.planned_labor_minor)}</b></div><div><span>{tx("Open diensten","Coverage gaps")}</span><b>{String(staffing.open_shifts??0)}</b></div><div><span>{tx("Geposte openingscounts","Posted opening counts")}</span><b>{String(inventory.opening_counts_posted??0)}</b></div></section>
      <section className="autopilot-summary"><div><span className={`operation-status ${op.status}`}>{op.status.replaceAll("_"," ")}</span><h3>{tx("Wat NightProfit heeft voorbereid","What NightProfit prepared")}</h3><p>{tx(`${demand.expected_guests??0} gasten en ${money(demand.expected_revenue_minor)} omzet; ${staffing.shift_count??0} diensten gepland, ${staffing.open_shifts??0} dekkingsgaten en ${op.missing_evidence.length} ontbrekende bewijsbron(nen).`,`${demand.expected_guests??0} guests and ${money(demand.expected_revenue_minor)} revenue; ${staffing.shift_count??0} shifts planned, ${staffing.open_shifts??0} coverage gaps and ${op.missing_evidence.length} missing evidence source(s).`)}</p><div className="evidence-links"><Link href="/app/planning">{tx("Roosterbewijs","Roster evidence")} →</Link><Link href="/app/inventory">{tx("Voorraadbewijs","Inventory evidence")} →</Link><Link href="/app/reconcile">{tx("Reconciliatiebewijs","Reconciliation evidence")} →</Link></div></div><div className="approval-box"><span>{tx("Geld op risico","Money at risk")}</span><b>{money(risk)}</b><small>{actions.length} {tx("gerangschikte acties","ranked actions")}</small>{op.status!=="approved"?<><textarea id="approval-reason" placeholder={tx("Reden voor besluit (verplicht)","Decision reason (required)")} defaultValue={tx("Plan gecontroleerd op actuele operationele feiten.","Plan reviewed against current operational facts.")}/><div><button disabled={busy} onClick={()=>{const reason=(document.getElementById("approval-reason") as HTMLTextAreaElement).value;void mutate({action:"decide",serviceOperationId:op.id,decision:"rejected",reason})}}>{tx("Terugsturen","Return")}</button><button className="primary" disabled={busy||op.missing_evidence.includes("demand_forecast")} onClick={()=>{const reason=(document.getElementById("approval-reason") as HTMLTextAreaElement).value;void mutate({action:"decide",serviceOperationId:op.id,decision:"approved",reason})}}>{tx("Plan goedkeuren","Approve plan")}</button></div></>:<strong>{tx("Door manager goedgekeurd","Manager approved")}</strong>}</div></section>
    </>}
    <section className="next-actions"><header><div><span className="eyebrow">NEXT BEST ACTION</span><h3>{tx("Alleen afwijkingen die een besluit vragen","Only deviations that need a decision")}</h3></div></header>{actions.length?<div>{actions.map((action,index)=><article key={action.id}><span className="action-rank">{index+1}</span><div><b>{action.title}</b><p>{action.rationale}</p><small>{action.why_it_matters}</small></div><div className="action-impact"><b>{action.expected_impact_minor?money(action.expected_impact_minor):tx("Impact te bepalen","Impact pending")}</b><span>{Math.round(action.evidence_completeness_basis_points/100)}% {tx("bewijs","evidence")}</span><Link href={action.action_type==="coverage_gap"?"/app/planning":"/app/inventory"}>{action.recommended_response??tx("Open actie","Open action")} →</Link></div></article>)}</div>:<div className="autopilot-empty"><p>{tx("Geen materiële afwijkingen met voldoende bewijs.","No material deviations with sufficient evidence.")}</p></div>}</section>
  </div>
}
