"use client";

import Link from "next/link";
import { useRouter } from "next/navigation";
import { useState } from "react";
import { useAuthLocale } from "./auth-locale";

type Snapshot=Record<string,unknown>;
type PurchaseLine={product_id:string;product_name:string;forecast_sales:number;required_quantity:number;available_quantity:number;outstanding_quantity:number;par_quantity:number;suggested_order_quantity:number;effective_unit_cost_minor:number;expected_purchase_cost_minor:number;evidence_completeness_basis_points:number};
type Operation={id:string;venue_id:string;service_date:string;stage:string;status:string;demand_snapshot:Snapshot;staffing_snapshot:Snapshot;consumption_snapshot:Snapshot;inventory_snapshot:Snapshot;purchasing_snapshot:Snapshot;live_snapshot:Snapshot;outcome_snapshot:Snapshot;readiness_checks:Array<Snapshot>;missing_evidence:string[];stale_reasons:string[]};
type Action={id:string;title:string;rationale:string;why_it_matters:string|null;recommended_response:string|null;severity:string;status:string;due_at:string|null;expected_impact_minor:string|null;evidence_completeness_basis_points:number;rank_score:string;action_type:string};
type Venue={id:string;name:string};

const stages=["prepare","open","run","close","learn"] as const;
export function ServiceAutopilot({organisationId,venues,initialOperation,actions}:{organisationId:string;venues:Venue[];initialOperation:Operation|null;actions:Action[]}){
  const {locale}=useAuthLocale(),router=useRouter(),tx=(nl:string,en:string)=>locale==="nl"?nl:en;
  const [venueId,setVenueId]=useState(initialOperation?.venue_id??venues[0]?.id??"");
  const [serviceDate,setServiceDate]=useState(initialOperation?.service_date??new Date().toISOString().slice(0,10));
  const [busy,setBusy]=useState(false),[message,setMessage]=useState("");
  const op=initialOperation;
  const demand=op?.demand_snapshot??{},staffing=op?.staffing_snapshot??{},inventory=op?.inventory_snapshot??{},consumption=op?.consumption_snapshot??{},purchasing=op?.purchasing_snapshot??{},live=op?.live_snapshot??{},outcome=op?.outcome_snapshot??{};
  const purchaseLines=Array.isArray(purchasing.lines)?purchasing.lines as PurchaseLine[]:[];
  const money=(minor:unknown)=>new Intl.NumberFormat(locale==="nl"?"nl-NL":"en-GB",{style:"currency",currency:"EUR",maximumFractionDigits:0}).format(Number(minor??0)/100);
  const number=(value:unknown)=>new Intl.NumberFormat(locale==="nl"?"nl-NL":"en-GB",{maximumFractionDigits:2}).format(Number(value??0));
  async function mutate(payload:Record<string,string>){setBusy(true);setMessage("");try{const response=await fetch("/api/service-operations",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({organisationId,venueId,...payload})});const result=await response.json() as {message?:string};if(!response.ok)throw new Error(tx("De actie kon niet worden voltooid.","The action could not be completed."));setMessage(result.message??tx("Opgeslagen.","Saved."));router.refresh()}catch(error){setMessage(error instanceof Error?error.message:tx("Opslaan mislukt.","Save failed."))}finally{setBusy(false)}}
  const risk=actions.reduce((sum,row)=>sum+Math.abs(Number(BigInt(row.expected_impact_minor??"0"))),0);
  const actualRevenue=Number(live.recorded_revenue_minor??0),forecastRevenue=Number(live.forecast_revenue_minor??demand.expected_revenue_minor??0);
  const revenueProgress=forecastRevenue>0?Math.min(100,Math.round(actualRevenue/forecastRevenue*100)):0;
  const actionHref=(type:string)=>type==="coverage_gap"?"/app/planning":type.includes("recon")?"/app/reconcile":"/app/inventory";
  return <div className="autopilot">
    <header className="autopilot-hero"><div><span className="eyebrow">{tx("VANDAAG","TODAY")}</span><h2>{op?tx(`${serviceDate} wordt voorbereid`,`${serviceDate} is being prepared`):tx("Bereid de volgende service voor","Prepare the next service")}</h2><p>{tx("NightProfit verzamelt de opgeslagen feiten, rekent behoeften uit en legt alleen echte besluiten voor.","NightProfit gathers persisted facts, calculates requirements and presents only real decisions.")}</p></div><div className="autopilot-context"><select aria-label={tx("Vestiging","Venue")} value={venueId} onChange={event=>setVenueId(event.target.value)}>{venues.map(v=><option key={v.id} value={v.id}>{v.name}</option>)}</select><input aria-label={tx("Servicedatum","Service date")} type="date" value={serviceDate} onChange={event=>setServiceDate(event.target.value)}/><button className="primary" disabled={busy||!venueId} onClick={()=>void mutate({action:"prepare",serviceDate})}>{op?tx("Alles opnieuw berekenen","Recalculate everything"):tx("Service voorbereiden","Prepare service")}</button></div></header>
    <nav className="service-rhythm" aria-label={tx("Servicefasen","Service stages")}>{stages.map(stage=><span key={stage} className={op?.stage===stage?"active":""}>{tx({prepare:"Voorbereiden",open:"Openen",run:"Service",close:"Afsluiten",learn:"Leren"}[stage],{prepare:"Prepare",open:"Open",run:"Run service",close:"Close",learn:"Learn"}[stage])}</span>)}</nav>
    {message?<p className="autopilot-message" role="status">{message}</p>:null}
    {!op?<section className="autopilot-empty"><h3>{tx("Nog geen service voorbereid","No service prepared yet")}</h3><p>{tx("Kies de datum. NightProfit gebruikt alleen opgeslagen omzet-, rooster- en voorraadgegevens.","Choose the date. NightProfit uses only persisted sales, roster and inventory data.")}</p></section>:<>
      <section className="decision-package"><div><span>{tx("Verwachte gasten","Expected guests")}</span><b>{String(demand.expected_guests??0)}</b></div><div><span>{tx("Omzetforecast","Revenue forecast")}</span><b>{money(demand.expected_revenue_minor)}</b></div><div><span>{tx("Geplande diensten","Planned shifts")}</span><b>{String(staffing.shift_count??0)}</b></div><div><span>{tx("Loonbudget","Labor budget")}</span><b>{money(staffing.planned_labor_minor)}</b></div><div><span>{tx("Voorraadtekorten","Stock shortages")}</span><b>{String(purchasing.shortage_count??0)}</b></div><div><span>{tx("Voorgestelde inkoop","Suggested purchasing")}</span><b>{money(purchasing.expected_spend_minor)}</b></div></section>
      <section className="today-grid">
        <article><span className="eyebrow">{tx("AL GEREGELD","ALREADY HANDLED")}</span><h3>{tx("Plan en berekeningen voorbereid","Plan and calculations prepared")}</h3><p>{tx(`${staffing.shift_count??0} diensten, ${purchaseLines.length} productbehoeften en ${inventory.opening_counts_posted??0} geposte openingscount(s) zijn gekoppeld.`,`${staffing.shift_count??0} shifts, ${purchaseLines.length} product requirements and ${inventory.opening_counts_posted??0} posted opening count(s) are linked.`)}</p></article>
        <article><span className="eyebrow">{tx("JOUW BESLUIT","NEEDS YOUR DECISION")}</span><h3>{actions.length+((purchasing.status==="ready_for_review")?1:0)} {tx("open besluiten","open decisions")}</h3><p>{purchasing.status==="ready_for_review"?tx(`Controleer het inkoopvoorstel van ${money(purchasing.expected_spend_minor)}.`,`Review the ${money(purchasing.expected_spend_minor)} purchasing proposal.`):tx("Er staat geen inkoopvoorstel klaar voor goedkeuring.","No purchasing proposal is awaiting approval.")}</p></article>
        <article><span className="eyebrow">{tx("RISICO'S","RISKS")}</span><h3>{money(risk)} {tx("zichtbare impact","visible impact")}</h3><p>{op.missing_evidence.length?tx(`${op.missing_evidence.length} bron(nen) ontbreken; NightProfit verzint daarvoor geen waarden.`,`${op.missing_evidence.length} source(s) are missing; NightProfit does not invent values.`):tx("Alle verplichte bronnen zijn aanwezig.","All required sources are present.")}</p></article>
      </section>
      <section className="autopilot-summary"><div><span className={`operation-status ${op.status}`}>{op.status.replaceAll("_"," ")}</span><h3>{tx("Serviceplan","Service plan")}</h3><p>{tx(`${demand.expected_guests??0} gasten en ${money(demand.expected_revenue_minor)} omzet; ${staffing.open_shifts??0} dekkingsgaten en ${op.missing_evidence.length} ontbrekende bron(nen).`,`${demand.expected_guests??0} guests and ${money(demand.expected_revenue_minor)} revenue; ${staffing.open_shifts??0} coverage gaps and ${op.missing_evidence.length} missing source(s).`)}</p><div className="evidence-links"><Link href="/app/planning">{tx("Rooster openen","Open roster")} →</Link><Link href="/app/inventory">{tx("Voorraad tellen","Count inventory")} →</Link><Link href="/app/reconcile">{tx("Afsluiten","Close service")} →</Link></div></div><div className="approval-box"><span>{tx("Planstatus","Plan status")}</span><b>{op.status.replaceAll("_"," ")}</b>{op.status!=="approved"?<><textarea id="approval-reason" aria-label={tx("Reden voor besluit","Decision reason")} defaultValue={tx("Plan gecontroleerd op de actuele operationele feiten.","Plan reviewed against the current operational facts.")}/><div><button disabled={busy} onClick={()=>{const reason=(document.getElementById("approval-reason") as HTMLTextAreaElement).value;void mutate({action:"decide",serviceOperationId:op.id,decision:"rejected",reason})}}>{tx("Terugsturen","Return")}</button><button className="primary" disabled={busy||op.missing_evidence.includes("demand_forecast")} onClick={()=>{const reason=(document.getElementById("approval-reason") as HTMLTextAreaElement).value;void mutate({action:"decide",serviceOperationId:op.id,decision:"approved",reason})}}>{tx("Plan goedkeuren","Approve plan")}</button></div></>:<strong>{tx("Door manager goedgekeurd","Manager approved")}</strong>}</div></section>
      <section className="live-pulse"><header><div><span className="eyebrow">{tx("VANAVOND","TONIGHT")}</span><h3>{tx("Live Profit Pulse","Live Profit Pulse")}</h3></div><button disabled={busy} onClick={()=>void mutate({action:"refresh",serviceOperationId:op.id})}>{tx("Live feiten verversen","Refresh live facts")}</button></header><div className="pulse-grid"><div><span>{tx("Geregistreerde omzet","Recorded revenue")}</span><b>{money(actualRevenue)}</b><small>{revenueProgress}% {tx("van forecast","of forecast")}</small></div><div><span>{tx("Gewerkte tijd","Worked time")}</span><b>{number(Number(live.worked_minutes??0)/60)}h</b><small>{money(live.actual_labor_minor)} {tx("loonkosten","labor cost")}</small></div><div><span>{tx("Bron bijgewerkt","Source updated")}</span><b>{live.source_updated_at?new Date(String(live.source_updated_at)).toLocaleTimeString(locale==="nl"?"nl-NL":"en-GB",{hour:"2-digit",minute:"2-digit"}):"—"}</b><small>{tx("Opgeslagen POS en tijdregistratie","Persisted POS and time records")}</small></div></div><div className="pulse-track" aria-label={`${revenueProgress}%`}><span style={{width:`${revenueProgress}%`}}/></div></section>
      <section className="purchasing"><header><div><span className="eyebrow">{tx("VERBRUIK & INKOOP","CONSUMPTION & PURCHASING")}</span><h3>{tx("Berekend uit verkoopmix, recepten en voorraad","Calculated from sales mix, recipes and stock")}</h3></div><b>{money(purchasing.expected_spend_minor)}</b></header>{purchaseLines.length?<div className="purchase-table" role="table"><div className="purchase-head" role="row"><span>{tx("Product","Product")}</span><span>{tx("Nodig","Required")}</span><span>{tx("Beschikbaar","Available")}</span><span>{tx("Bestel","Order")}</span><span>{tx("Kosten","Cost")}</span><span>{tx("Bewijs","Evidence")}</span></div>{purchaseLines.slice(0,12).map(line=><div key={line.product_id} role="row"><b>{line.product_name}</b><span>{number(line.required_quantity)}</span><span>{number(line.available_quantity)}</span><strong>{number(line.suggested_order_quantity)}</strong><span>{money(line.expected_purchase_cost_minor)}</span><span>{Math.round(line.evidence_completeness_basis_points/100)}%</span></div>)}</div>:<p className="quiet">{Number(consumption.missing_recipe_count??0)>0?tx("Maak ontbrekende recepten compleet om productbehoeften te berekenen.","Complete missing recipes to calculate product requirements."):tx("Nog geen verkoopmix met gekoppelde recepten beschikbaar.","No sales mix with linked recipes is available yet.")}</p>}{purchasing.status==="ready_for_review"&&purchasing.plan_id?<div className="purchase-approval"><textarea id="purchase-reason" aria-label={tx("Reden voor inkoopbesluit","Purchasing decision reason")} defaultValue={tx("Hoeveelheden, voorraad en kostprijzen gecontroleerd.","Quantities, stock and costs reviewed.")}/><button className="primary" disabled={busy} onClick={()=>{const reason=(document.getElementById("purchase-reason") as HTMLTextAreaElement).value;void mutate({action:"decide_purchase",planId:String(purchasing.plan_id),decision:"approved",reason})}}>{tx("Inkoopvoorstel goedkeuren","Approve purchasing proposal")}</button><small>{tx("Goedkeuren plaatst of verstuurt nog geen bestelling.","Approval does not place or send an order.")}</small></div>:null}</section>
      {Object.keys(outcome).length?<section className="learn-card"><span className="eyebrow">{tx("GISTEREN","YESTERDAY")}</span><h3>{tx("Leren uit de vergrendelde afsluiting","Learn from the locked close")}</h3><div><span>{tx("Forecast omzet","Forecast revenue")} <b>{money(outcome.forecast_revenue_minor)}</b></span><span>{tx("Werkelijke omzet","Actual revenue")} <b>{money(outcome.actual_revenue_minor)}</b></span><span>{tx("Marge-impact","Margin impact")} <b>{money(outcome.margin_impact_minor)}</b></span></div><p>{String(outcome.lesson??"")}</p></section>:null}
    </>}
    <section className="next-actions"><header><div><span className="eyebrow">{tx("VOLGENDE BESTE ACTIE","NEXT BEST ACTION")}</span><h3>{tx("Alleen afwijkingen die een besluit vragen","Only deviations that need a decision")}</h3></div></header>{actions.length?<div>{actions.map((action,index)=><article key={action.id}><span className="action-rank">{index+1}</span><div><b>{action.title}</b><p>{action.rationale}</p><small>{action.why_it_matters}</small></div><div className="action-impact"><b>{action.expected_impact_minor?money(action.expected_impact_minor):tx("Impact te bepalen","Impact pending")}</b><span>{Math.round(action.evidence_completeness_basis_points/100)}% {tx("bewijs","evidence")}</span><Link href={actionHref(action.action_type)}>{action.recommended_response??tx("Open actie","Open action")} →</Link></div></article>)}</div>:<div className="autopilot-empty"><p>{tx("Geen materiële afwijkingen met voldoende bewijs.","No material deviations with sufficient evidence.")}</p></div>}</section>
  </div>
}
