"use client";
import {useMemo,useState} from "react";
type Entry={startsAt:string;endsAt:string;availability:"available"|"preferred"|"unavailable";note:string};
export function AvailabilityResponse({token,periodStart,periodEnd,venueName}:{token:string;periodStart:string;periodEnd:string;venueName:string}){
  const days=useMemo(()=>{const result:string[]=[];const cursor=new Date(periodStart),end=new Date(periodEnd);while(cursor<end&&result.length<31){result.push(cursor.toISOString().slice(0,10));cursor.setUTCDate(cursor.getUTCDate()+1)}return result},[periodStart,periodEnd]);
  const [entries,setEntries]=useState<Entry[]>(days.map(day=>({startsAt:`${day}T09:00:00.000Z`,endsAt:`${day}T17:00:00.000Z`,availability:"available",note:""})));
  const [review,setReview]=useState(false),[pending,setPending]=useState(false),[message,setMessage]=useState(""),[error,setError]=useState("");
  const update=(index:number,patch:Partial<Entry>)=>setEntries(current=>current.map((entry,i)=>i===index?{...entry,...patch}:entry));
  async function submit(){setPending(true);setError("");const response=await fetch("/api/availability/respond",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({token,periodStart,periodEnd,entries})});const result=await response.json() as {error?:string;message?:string};setPending(false);if(!response.ok){setError(result.error||"Versturen is niet gelukt.");return}setMessage(result.message||"Bevestigd.")}
  if(message)return <main className="availability-page"><section className="availability-card success-card"><div className="logo">N</div><p className="eyebrow">BEVESTIGD</p><h1>Beschikbaarheid ontvangen</h1><p>{message} Je kunt dit venster sluiten.</p></section></main>;
  return <main className="availability-page"><section className="availability-card"><div className="logo">N</div><p className="eyebrow">NIGHTPROFIT · {venueName}</p><h1>{review?"Controleer je periode":"Wanneer kun je werken?"}</h1><p>Geef per dag je voorkeur aan. Alleen je planner ziet deze informatie.</p>
    {!review?<div className="availability-days">{entries.map((entry,index)=><fieldset key={days[index]}><legend>{new Date(`${days[index]}T12:00:00Z`).toLocaleDateString("nl-NL",{weekday:"long",day:"numeric",month:"long"})}</legend><label>Status<select value={entry.availability} onChange={e=>update(index,{availability:e.target.value as Entry["availability"]})}><option value="available">Beschikbaar</option><option value="preferred">Bij voorkeur</option><option value="unavailable">Niet beschikbaar</option></select></label><label>Van<input type="time" value={entry.startsAt.slice(11,16)} onChange={e=>update(index,{startsAt:`${days[index]}T${e.target.value}:00.000Z`})}/></label><label>Tot<input type="time" value={entry.endsAt.slice(11,16)} onChange={e=>update(index,{endsAt:`${days[index]}T${e.target.value}:00.000Z`})}/></label><label className="wide">Toelichting (optioneel)<input value={entry.note} maxLength={500} onChange={e=>update(index,{note:e.target.value})}/></label></fieldset>)}</div>:<div className="availability-review">{entries.map((entry,index)=><div key={days[index]}><b>{new Date(`${days[index]}T12:00:00Z`).toLocaleDateString("nl-NL",{weekday:"long",day:"numeric",month:"short"})}</b><span>{entry.availability} · {entry.startsAt.slice(11,16)}–{entry.endsAt.slice(11,16)}</span></div>)}</div>}
    {error&&<p className="form-error" role="alert">{error}</p>}<div className="action-bar">{review?<button className="ghost" type="button" onClick={()=>setReview(false)}>Terug</button>:null}<button className="primary" type="button" disabled={pending} onClick={()=>review?submit():setReview(true)}>{pending?"Versturen…":review?"Definitief versturen":"Periode controleren"}</button></div>
  </section></main>;
}
